import { Box, Button, Grid, OutlinedInput, Typography } from '@mui/material'
import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'

const ControlData = ({ data, setData }) => {
    const navigate = useNavigate()

    const inputHandler = (e) => {
        const { name, value } = e.target;

        setData({ ...data, [name]: value })
    }
    console.log(data)


    return (
        <>
            <Grid container sx={{ justifyContent: "center" }}>
                <Grid item xs={7} sx={{ p: "20px", border: "1px solid black" }}>
                    <Box>
                        <Typography align='center' sx={{ fontSize: "30px", fontWeight: "bold", mt: "10px" }}>
                            Bill Data
                        </Typography>
                    </Box>
                    <Box sx={{ mt: "40px" }}>
                        {/* input1 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                            E-Way Bill No:
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input1' value={data.input1} placeholder='Enter data...' />

                        {/* input2 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                            E-Way Bill Date:
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input2' value={data.input2} placeholder='Enter data...' />

                        {/* input3 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                            Generated By:
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input3' value={data.input3} placeholder='Enter data...' />


                        {/* input4 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                            Valid From:
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input4' value={data.input4} placeholder='Enter data...' />


                        {/* input5 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                            Valid Until:
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input5' value={data.input5} placeholder='Enter data...' />


                        {/* input6 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                            GSTIN of Supplier
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input6' value={data.input6} placeholder='Enter data...' />


                        {/* input7 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                            Place of Dispatch
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input7' value={data.input7} placeholder='Enter data...' />


                        {/* input8 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                            GSTIN of Recipient
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input8' value={data.input8} placeholder='Enter data...' />



                        {/* input9 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                            Place of Delivery
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input9' value={data.input9} placeholder='Enter data...' />


                        {/* input10 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                            Document No.
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input10' value={data.input10} placeholder='Enter data...' />


                        {/* input11 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                            Document Date
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input11' value={data.input11} placeholder='Enter data...' />


                        {/* input12 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                            Transaction Type:
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input12' value={data.input12} placeholder='Enter data...' />

                        {/* input13 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                            Value of Goods
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input13' value={data.input13} placeholder='Enter data...' />

                        {/* input14 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                            HSN Code
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input14' value={data.input14} placeholder='Enter data...' />

                        {/* input15 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                            Reason for Transportation
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input15' value={data.input15} placeholder='Enter data...' />

                        {/* input16 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                            Transporter
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input16' value={data.input16} placeholder='Enter data...' />


                        {/* input17 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                            Mode
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input17' value={data.input17} placeholder='Enter data...' />

                        {/* input18 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                            Vehicle / Trans Doc No & Dt.
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input18' value={data.input18} placeholder='Enter data...' />

                        {/* input19 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                            From
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input19' value={data.input19} placeholder='Enter data...' />

                        {/* input20 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                            Entered Date
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input20' value={data.input20} placeholder='Enter data...' />


                        {/* input21 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                            Entered By
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input21' value={data.input21} placeholder='Enter data...' />
                        
                        
                        {/* input22 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                            CEWB No.(If any)
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input22' value={data.input22} placeholder='Enter data...' />

                        {/* input23 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                            MultiVeh.Info(If any)
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input23' value={data.input23} placeholder='Enter data...' />


                           {/* input24 */}
                           <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                            Scanner
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input24' value={data.input24} placeholder='Enter data...' />

                    </Box>

                    <Box sx={{mt:"20px", display:"flex",justifyContent:"center"}}>
                         <Button variant='contained' onClick={()=>{navigate('/form')}}>
                            View
                         </Button>
                    </Box>
                </Grid>
            </Grid>
        </>
    )
}

export default ControlData