import { Box, Button, Grid, OutlinedInput, Typography } from '@mui/material'
import { useNavigate } from 'react-router-dom'


const ControlSecondForm = ({formData,setFormData}) => {
    const navigate = useNavigate()
  

    const inputHandler = (e) => {
        const { name, value } = e.target;

        setFormData({ ...formData, [name]: value })
    }
    // console.log(formData)


    return (
        <>
            <Grid container sx={{ justifyContent: "center" }}>
                <Grid item xs={7} sx={{ p: "20px", border: "1px solid black" }}>
                    <Box>
                        <Typography align='center' sx={{ fontSize: "30px", fontWeight: "bold", mt: "10px" }}>
                            Bill Form
                        </Typography>
                    </Box>
                    <Box sx={{ mt: "40px" }}>
                        {/* input1 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        eWay Bill No:
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input1' value={formData.input1} placeholder='Enter formData...' />

                        {/* input2 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        Generated Date:
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input2' value={formData.input2} placeholder='Enter formData...' />

                        {/* input3 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        Generated By:
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input3' value={formData.input3} placeholder='Enter formData...' />


                        {/* input4 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        Valid Upto:
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input4' value={formData.input4} placeholder='Enter formData...' />


                        {/* input5 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        Mode:
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input5' value={formData.input5} placeholder='Enter formData...' />


                        {/* input6 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        Approx Distance:
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input6' value={formData.input6} placeholder='Enter formData...' />


                        {/* input7 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        Type:
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input7' value={formData.input7} placeholder='Enter formData...' />


                        {/* input8 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        Document Details:
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input8' value={formData.input8} placeholder='Enter formData...' />



                        {/* input9 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        Transaction type:
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input9' value={formData.input9} placeholder='Enter formData...' />


                        {/* input10 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        GSTIN :
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input10' value={formData.input10} placeholder='Enter formData...' />
                        <OutlinedInput onChange={inputHandler} fullWidth name='input10a' value={formData.input10a} placeholder='Enter Name...' />
                        <OutlinedInput onChange={inputHandler} fullWidth name='input10b' value={formData.input10b} placeholder='Enter state...' />
                        <OutlinedInput onChange={inputHandler} fullWidth name='input10c' value={formData.input10c} placeholder='Enter 1...' />
                        <OutlinedInput onChange={inputHandler} fullWidth name='input10d' value={formData.input10d} placeholder='Enter 2...' />
                        <OutlinedInput onChange={inputHandler} fullWidth name='input10e' value={formData.input10e} placeholder='Enter 3...' />
                        


                        {/* input11 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        GSTIN :
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input11' value={formData.input11} placeholder='Enter formData...' />
                        <OutlinedInput onChange={inputHandler} fullWidth name='input11a' value={formData.input11a} placeholder='Enter Name...' />
                        <OutlinedInput onChange={inputHandler} fullWidth name='input11b' value={formData.input11b} placeholder='Enter state...' />
                        <OutlinedInput onChange={inputHandler} fullWidth name='input11c' value={formData.input11c} placeholder='Enter 1...' />
                        <OutlinedInput onChange={inputHandler} fullWidth name='input11d' value={formData.input11d} placeholder='Enter 2...' />
                        <OutlinedInput onChange={inputHandler} fullWidth name='input11e' value={formData.input11e} placeholder='Enter 3...' />

                        {/* input12 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        HSN Code

                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input12' value={formData.input12} placeholder='Enter formData...' />

                        {/* input13 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        Product Name & Desc. 
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input13' value={formData.input13} placeholder='Enter formData...' />

                        {/* input14 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        Quantity
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input14' value={formData.input14} placeholder='Enter formData...' />

                        {/* input15 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        Taxable Amount
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input15' value={formData.input15} placeholder='Enter formData...' />

                        {/* input16 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        Tax Rate (C+S+I+Cess+Cess Non.Advol)
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input16' value={formData.input16} placeholder='Enter formData...' />


                        {/* input17 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        Tot. Tax'ble Amt 
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input17' value={formData.input17} placeholder='Enter formData...' />

                        {/* input18 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        CGST Amt
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input18' value={formData.input18} placeholder='Enter formData...' />

                        {/* input19 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        SGST Amt
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input19' value={formData.input19} placeholder='Enter formData...' />

                        {/* input20 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        IGST Amt
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input20' value={formData.input20} placeholder='Enter formData...' />


                        {/* input21 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        CESS Amt
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input21' value={formData.input21} placeholder='Enter formData...' />
                        
                        
                        {/* input22 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        CESS Non.Advol Amt
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input22' value={formData.input22} placeholder='Enter formData...' />

                        {/* input23 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        Other Amt
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input23' value={formData.input23} placeholder='Enter formData...' />
                         {/* input 24 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        Total Inv.Amt
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input24' value={formData.input24} placeholder='Enter formData...' />

                        {/* input 25 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        Transporter ID & Name :
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input25' value={formData.input25} placeholder='Enter formData...' />

                        {/* input 26 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        Transporter Doc. No & Date :
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input26' value={formData.input26} placeholder='Enter formData...' />

                        {/* input 27 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        Mode
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input27' value={formData.input27} placeholder='Enter formData...' />

                        {/* input 28 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        Vehicle / Trans Doc No & Dt
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input28' value={formData.input28} placeholder='Enter formData...' />

                        {/* input 29 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        From
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input29' value={formData.input29} placeholder='Enter formData...' />

                        {/* input 30 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        Entered Date
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input30' value={formData.input30} placeholder='Enter formData...' />

                        {/* input 31 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        Entered By
                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input31' value={formData.input31} placeholder='Enter formData...' />

                        {/* input 32 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        CEWB No.(If any)

                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input32' value={formData.input32} placeholder='Enter formData...' />

                        {/* input 33 */}
                        <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                        Multi Veh.Info(If any)

                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input33' value={formData.input33} placeholder='Enter formData...' />


                         {/* input 34 */}
                         <Typography sx={{ fontSize: "19px", mt: "15px" }}>
                         Scanner Code

                        </Typography>
                        <OutlinedInput onChange={inputHandler} fullWidth name='input34' value={formData.input34} placeholder='Enter formData...' />
                    </Box>

                    <Box sx={{mt:"20px", display:"flex",justifyContent:"center"}}>
                         <Button variant='contained' onClick={()=>{navigate('/secondform')}}>
                            View
                         </Button>
                    </Box>
                </Grid>
            </Grid>

            
        </>
    )
}

export default ControlSecondForm